name: aplikasi_cafe
description: "Aplikasi kafe dibuat dengan menggunakan flutter."

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/images/nostalgia/
    - assets/images/koat/
    - assets/images/for-good-luck/
    - assets/images/loer/
    - assets/images/nako/
    - assets/images/sanjo/
    - assets/images/nagara/
    - assets/images/soree/
    - assets/images/taki/
    - assets/images/cce-space/
    - assets/images/dayone/
    - assets/images/days-cafe/
    - assets/images/eightynine/
    - assets/images/enamdua/
    - assets/images/kopi-dari-hati/
    - assets/images/luthier/
    - assets/images/york-cafe/